module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [2, 'always', ['feat', 'fix', 'docs', 'chore', 'test']],
    'scope-enum': [2, 'always', ['feat', 'fix', 'docs', 'chore', 'test']],
    'subject-case': [2, 'always', 'sentence-case'],
    'header-max-length': [2, 'always', 72],
    'footer-max-line-length': [2, 'always', 72],
    'subject-full-stop': [2, 'never'],
    'type-empty': [2, 'never'],
    'scope-empty': [2, 'never'],
    'subject-empty': [2, 'never'],
    'body-empty': [2, 'never'],
    'footer-empty': [2, 'never'],
    'type-case': [2, 'always', 'lower-case'],
    'scope-case': [2, 'always', 'kebab-case'],
    'scope-enum': [2, 'always', ['feat', 'fix', 'docs', 'chore', 'test']],
    'references-empty': [2, 'never'],
    'signed-off-by': [2, 'never'],
    'max-lines': [2, 'always', 1],
    'footer-leading-blank': [2, 'always'],
    'header-max-length': [2, 'always', 72],
    'body-max-line-length': [2, 'always', 72],
    'subject-max-line-length': [2, 'always', 72],
    'references-full-stop': [2, 'never'],
    'signed-off-by-empty': [2, 'never'],
    'header-full-stop': [2, 'never'],
    'scope-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    'type-enum': [2, 'always', ['feat', 'fix', 'docs', 'chore', 'test']],
    'type-case': [2, 'always', 'lower-case'],
    'type-max-length': [2, 'always', 12],
    'type-min-length': [2, 'always', 2],
    'subject-empty': [2, 'never'],
    'subject-case': [2, 'always', 'sentence-case'],
    'subject-max-length': [2, 'always', 72],
    'subject-min-length': [2, 'always', 5],
    'footer-empty': [2, 'never'],
    'footer-leading-blank': [2, 'always'],
    'footer-max-line-length': [2, 'always', 72],
    'footer-min-length': [2, 'always', 5],
    'body-empty': [2, 'never'],
    'body-leading-blank': [2, 'always'],
    'body-max-line-length': [2, 'always', 72],
    'body-min-length': [2, 'always', 5],
  },
}
