name: Run commitlint on pull request 

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-commitlint-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Validate all commits from PR
        run: >
          for commit in $(git rev-list ${{ github.base_ref }}..${{
          github.head_ref }}); do
              npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD --verbose
          done